### PR TITLE
Documentation for modifier keys

### PR DESCRIPTION
**Pull request by aurelienbottazini**
Documentation to support https://github.com/zeit/hyperterm/pull/686

cursor_and_hyperterm

### CODE REVIEW

**Comment by rauchg** [comment]
+1

**Comment by CodeTheory** [comment]
@aurelienbottazini Could you rebase, please?

**Comment by leo** [comment]
@aurelienbottazini Please rebase 😊

**Comment by aurelienbottazini** [comment]
Sorry, did not see the first message :)

**Comment by CodeTheory** [comment]
No worries @aurelienbottazini! Thanks for your contribution!

**Pull request merged**
