### PR TITLE
Fix doc about plugin method names HyperTerm -> Hyper

### PR DESCRIPTION
**Pull request by chabou**
old method names are deprecated

### CODE REVIEW

**Comment by leo** [comment]
Hey!

**Comment by iamstarkov** [comment]
though, i think we need to say what are the prev methods which are deprecated and have been renamed. this will help plugins' authors to rename their methods easier

**Comment by chabou** [comment]
There is already warning/error in console. But yes, we could explicit this in doc.

**Comment by iamstarkov** [comment]
what kind of warning/error you are talking about?

**Comment by chabou** [comment]
these : https://github.com/zeit/hyper/blob/master/lib/utils/plugins.js#L120
This is enough imo

**Comment by chabou** [comment]
this is enough for plugins' author but not for a new comer who look a plugin (deprecated) code to learn. We definitely need to add these informations.

**Comment by iamstarkov** [comment]
yep

**Pull request merged**
