### PR TITLE
add css to external file

### PR DESCRIPTION
**Pull request by Koltharius**
Add css to external file #42

### CODE REVIEW

**Comment by tomByrer** [comment]
I guess slightly easier to maintain, but does it make the website load faster, in light of HTTP/2 (which I assume zeit has turned on like a good webhost ;) ?

**Comment by Koltharius** [comment]
Yes, the website load faster if the css are in external file

**Comment by matheuss** [comment]
@CodeTheory please review

**Comment by CodeTheory** [comment]
This is slightly hard to review @matheuss @Koltharius since there are so many HTML changes. The changes that this PR are meant to achieve but the rest is really hard to review. Is there anyway you can undo those changes and just let this PR be the "CSS in a file" change?

**Pull request closed without merging**
