### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by CodeTheory**
@leo This PR adds an MIT license to this repo. 🎉

### CODE REVIEW

**Comment by leo** [comment]
Thanks! But legally, I honestly don't think the "... and contributors" makes any sense. Technically, we would then have to ask every contributor for permissions if we want to delete/move/rename/remix/whatever the repo. Or am I wrong? 😄 

I saw this a few times on a few repos in the org (licenses contributed by collaborators), but yea...

**Comment by leo** [comment]
@CodeTheory No idea... Want to take a look at the history? But I definitely think we should change it.

**Comment by CodeTheory** [comment]
I agree @leo. Made the change after looking at other examples of MIT licenses. 👍

**Comment by leo** [comment]
Thanks! ❤️ Feel free to adjust this everywhere you see it.

**Pull request merged**
